<a href="https://colab.research.google.com/github/thecodemaster152/Brief-guide-to-tensor-flow/blob/main/00_tensorFlow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("lets start")

lets start


In [3]:
# importing tensorflow
import tensorflow as tf

##Creating Tensor

At first creating tensor with tf.constant()

In [4]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
#checking number of dimension of a tensor
scalar.ndim

0

In [8]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

notice here, shape of vector is (2,) ansd not just (2) bcoz, shape of tensor is stored in tuple always

In [9]:
vector.ndim

1

In [12]:
matrix = tf.constant([[2,3],[3,2]])
matrix.shape

TensorShape([2, 2])

In [13]:
matrix.ndim

2

In [19]:
#creating another matrix
another_matrix = tf.constant([[1,2,3],[1,2,3],[1,2,3]], dtype = tf.float32)

In [20]:
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]], dtype=float32)>

In [21]:
another_matrix.ndim

2

This was all about tf.constant now lets see tf.variable()


In [25]:
changeable_tensor = tf.Variable([2,3])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

In [27]:
changeable_tensor[0].assign(4)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 3], dtype=int32)>